# Nom du workflow
name: envoi_email

on:
  workflow_dispatch:
  
# que fait le workflow

jobs:
    envoi_email:
      permissions:
        contents: write
        pages: write
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.0
          with:
            name: point_collecte.pdf
            path: point_collecte.pdf

        - name: Envoi de mail
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            username: ${{secrets.MAIL_USERNAME_GHA}}
            password: ${{secrets.MAIL_PASSWORD_GHA}}
            subject: Point de la collecte des données
            to: armanddavy7@gmail.com
            from: Armand Davy
            body: Veuillez trouver ci-joint le point de la collecte de ce jour
            cc: ilgatbad@gmail.com
            ignore_cert: true
            convert_markdown: true
            attachments: point_collecte.pdf
            priority: low
            